language: erlang
otp_release:
  - 18.3
  - 17.5
  - R16B03-1

script:
  - ./rebar3 eunit
  - ./rebar3 ct

install:
  - URL='https://aphyr.com/riemann/riemann_0.2.11_all.deb'; FILE=`mktemp`; DEBIAN_FRONTEND=noninteractive; wget "$URL" -qO $FILE && sudo dpkg -i $FILE; rm $FILE
before_script:
  - sudo service riemann start
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3 
after_success:
  - rebar3 cover
